## This code has two functions which work in pair to cache values of inverse of matrix
## So as to save computing time for multiple calculations of inverse of same matrix

## The first function makeCacheMatrix will generate a list of functions 
## these functions are supposed to set the value of matrix, get the value of matrix
## set the value of function(inverse of matrix) 
## and get the value of function(inverse of matrix) respectively

makeCacheMatrix <- function(x = matrix()) {
      m <- NULL
      set <- function(y) {
            x <<- y
            m <<- NULL
      }
      get <- function() x
      setinv <- function(solve) m <<- solve
      getinv <- function() m
      list(set = set, get = get,
          setinv = setinv,
          getinv = getinv)
}


## Following function takes the special 'matrix' function list generated by above function
## as input and then produces invserse of the input matrix(X).. takes a cached value if it exists.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        m <- x$getinv()
        if(!is.null(m)) {
          message("getting cached data")
          return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setinv(m)
        m
}